# Agent 名称
name: 智能小助手
# Agent 模型标识
model: deepseek-v3-function-call
# Agent 设定
agentSetting: 你什么都知道，无论用户问你什么问题，你都能输出长篇大论，滔滔不绝。
# Agent 介绍
introduction: 你什么都知道，无论用户问你什么问题，你都能输出长篇大论，滔滔不绝。
# Agent 欢迎语
welcomeMessage: 你什么都知道，无论用户问你什么问题，你都能输出长篇大论，滔滔不绝。
# Agent 头像
avatar: ''
# Agent 初始化问题配置
initQuestions:
  - 你好，请介绍一下你自己。
  - 你好，你能帮我回答什么问题?
# Agent 开启推荐问题功能
isNeedRecommend: true
# Agent 绑定知识库
knowledgeBase: ['your-knowledge-base-id']
# Agent 绑定数据模型
databaseModel: ['your-database-model-id']
# Agent 开启联网搜送功能
searchNetworkEnable: true
# Agent 开启文件对话功能
searchFileEnable: true
mcpServerList:
  - tools:
      - name: 'geocoder'
      - name: 'placeSuggestion'
    url: https://luke-agent-dev-7g1nc8tqc2ab76af.api.tcloudbasegateway.com/v1/cloudrun/mcp-tencent-map-xunif0/messages
    name: 'mcp-tencent-map-xunif0'
    transport: 'post'
  - tools:
      - name: 'generate'
    url: https://luke-agent-dev-7g1nc8tqc2ab76af.api.tcloudbasegateway.com/v1/cloudrun/mcp-mermaid-ceh7gc/messages
    name: 'mcp-mermaid-ceh7gc'
    transport: 'streamable'
  - tools:
      - name: 'puppeteer_navigate'
    url: https://luke-agent-dev-7g1nc8tqc2ab76af.api.tcloudbasegateway.com/v1/cloudrun/mcp-puppeteer-hqqgrn/messages
    name: 'mcp-puppeteer-hqqgrn'
    transport: 'sse'